export const getMockDevelopers = () => {
  return [
    {
      id: 1,
      name: 'Alex Morgan',
      title: 'Full Stack Developer',
      location: 'San Francisco, CA',
      experienceLevel: '5-7 years',
      avatar: 'https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1534&q=80',
      skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'GraphQL', 'AWS'],
      bio: "Full stack developer with a passion for clean code and modern architecture. I specialize in React and Node.js applications with a focus on scalability and performance.",
      lookingFor: ['Open Source Projects', 'Startup Opportunities', 'Hackathon Partners'],
      githubUrl: 'https://github.com/alexmorgan',
      portfolioUrl: 'https://alexmorgan.dev'
    },
    {
      id: 2,
      name: 'Taylor Chen',
      title: 'UX/UI Designer & Frontend Dev',
      location: 'New York, NY',
      experienceLevel: '3-5 years',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1376&q=80',
      skills: ['UI Design', 'Figma', 'CSS', 'SASS', 'React', 'Next.js', 'Responsive Design'],
      bio: "Designer-developer hybrid focused on creating beautiful, intuitive interfaces. I believe in design systems and component-driven development to bridge the gap between design and engineering.",
      lookingFor: ['Design Systems', 'Frontend Projects', 'Creative Collaborations'],
      githubUrl: 'https://github.com/taylorchen',
      portfolioUrl: 'https://taylorchen.design'
    },
    {
      id: 3,
      name: 'Jordan Rivera',
      title: 'Mobile Developer',
      location: 'Austin, TX',
      experienceLevel: '4-6 years',
      avatar: 'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
      skills: ['React Native', 'Swift', 'Kotlin', 'Firebase', 'Redux', 'Mobile Design'],
      bio: "Mobile developer specialized in cross-platform apps with React Native. I've shipped apps used by thousands of users and love creating smooth, native-feeling experiences across iOS and Android.",
      lookingFor: ['App Ideas', 'Mobile Projects', 'Startup Collaborations'],
      githubUrl: 'https://github.com/jordanrivera',
      portfolioUrl: 'https://jordanrivera.io'
    },
    {
      id: 4,
      name: 'Cameron Lee',
      title: 'Backend Engineer',
      location: 'Seattle, WA',
      experienceLevel: '7+ years',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
      skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS', 'Microservices', 'CI/CD'],
      bio: "Backend engineer focused on building robust, scalable APIs and services. Expert in Python with a strong DevOps background. I enjoy solving complex architectural challenges and performance optimization.",
      lookingFor: ['API Projects', 'System Architecture', 'Mentoring Opportunities'],
      githubUrl: 'https://github.com/cameronlee',
      portfolioUrl: 'https://cameronlee.tech'
    },
    {
      id: 5,
      name: 'Casey Wilson',
      title: 'Data Scientist & ML Engineer',
      location: 'Boston, MA',
      experienceLevel: '4-6 years',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
      skills: ['Python', 'TensorFlow', 'PyTorch', 'Data Science', 'Machine Learning', 'SQL', 'Data Visualization'],
      bio: "Data scientist with a focus on machine learning applications. I combine strong statistical knowledge with engineering skills to build end-to-end ML solutions. Currently interested in NLP and computer vision projects.",
      lookingFor: ['ML Projects', 'Research Collaborations', 'Hackathons'],
      githubUrl: 'https://github.com/caseywilson',
      portfolioUrl: 'https://caseywilson.ai'
    },
    {
      id: 6,
      name: 'Riley Johnson',
      title: 'DevOps Engineer',
      location: 'Denver, CO',
      experienceLevel: '6-8 years',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
      skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Linux', 'Python'],
      bio: "DevOps engineer passionate about automation and infrastructure as code. I build reliable, secure, and self-healing cloud infrastructure with a focus on AWS environments.",
      lookingFor: ['Infrastructure Projects', 'Cloud Architecture', 'Automation Challenges'],
      githubUrl: 'https://github.com/rileyjohnson',
      portfolioUrl: 'https://rileyjohnson.dev'
    },
    {
      id: 7,
      name: 'Avery Martinez',
      title: 'Frontend Engineer',
      location: 'Portland, OR',
      experienceLevel: '3-5 years',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1461&q=80',
      skills: ['React', 'TypeScript', 'Next.js', 'CSS', 'Redux', 'Testing', 'Web Performance'],
      bio: "Frontend engineer focused on creating fast, accessible, and beautiful web experiences. I'm passionate about design systems, web performance, and modern JavaScript frameworks.",
      lookingFor: ['Frontend Challenges', 'Performance Optimization', 'Mentorship'],
      githubUrl: 'https://github.com/averymartinez',
      portfolioUrl: 'https://averymartinez.com'
    },
    {
      id: 8,
      name: 'Jamie Parker',
      title: 'Blockchain Developer',
      location: 'Miami, FL',
      experienceLevel: '2-4 years',
      avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
      skills: ['Solidity', 'Ethereum', 'Web3.js', 'Smart Contracts', 'JavaScript', 'React', 'Blockchain'],
      bio: "Blockchain developer specializing in Ethereum and smart contracts. I'm passionate about decentralized finance and building the future of web3. Currently exploring NFT platforms and DAOs.",
      lookingFor: ['DeFi Projects', 'NFT Platforms', 'Web3 Startups'],
      githubUrl: 'https://github.com/jamieparker',
      portfolioUrl: 'https://jamieparker.eth.limo'
    },
    {
      id: 9,
      name: 'Quinn Nguyen',
      title: 'Game Developer',
      location: 'Los Angeles, CA',
      experienceLevel: '4-6 years',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80',
      skills: ['Unity', 'C#', '3D Modeling', 'Game Design', 'AR/VR', 'WebGL', 'Game Dev'],
      bio: "Game developer with experience in Unity and WebGL. I create interactive experiences for web, mobile, and VR platforms. Passionate about game mechanics and creating engaging player experiences.",
      lookingFor: ['Game Projects', 'Interactive Experiences', 'AR/VR Development'],
      githubUrl: 'https://github.com/quinnnguyen',
      portfolioUrl: 'https://quinnnguyen.games'
    },
    {
      id: 10,
      name: 'Reese Kim',
      title: 'Security Engineer',
      location: 'Chicago, IL',
      experienceLevel: '5-7 years',
      avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80',
      skills: ['Penetration Testing', 'Python', 'Network Security', 'Cryptography', 'Security Audits', 'Linux'],
      bio: "Security engineer focused on finding and fixing vulnerabilities before they become problems. I have experience with penetration testing, security audits, and implementing secure-by-design principles.",
      lookingFor: ['Security Challenges', 'Code Audits', 'Security Training'],
      githubUrl: 'https://github.com/reesekim',
      portfolioUrl: 'https://reesekim.security'
    }
  ];
};